apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: echo-service
          imagePullPolicy: "Always"
          image: hakeemsyd/echo-service
          ports:
            - containerPort: 3000
